package Onibus;

/**
 * Created by Gustavo on 14/08/2016.
 */
public enum Linha {
    L11(Ponto.CAMPUS_SANTO_ANDRE,Ponto.TERMINAL_LESTE),
    L12(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SANTO_ANDRE),

    L21(Ponto.CAMPUS_SANTO_ANDRE,Ponto.TERMINAL_LESTE),
    L22(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SAO_BERNARDO),
    L23(Ponto.CAMPUS_SAO_BERNARDO,Ponto.TERMINAL_LESTE),
    L24(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SANTO_ANDRE),

    L31(Ponto.CAMPUS_SANTO_ANDRE,Ponto.TERMINAL_LESTE),
    L32(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SAO_BERNARDO),
    L33(Ponto.CAMPUS_SAO_BERNARDO,Ponto.TERMINAL_LESTE),
    L34(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SANTO_ANDRE),

    L41(Ponto.CAMPUS_SANTO_ANDRE,Ponto.TERMINAL_LESTE),
    L42(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SAO_BERNARDO),
    L43(Ponto.CAMPUS_SAO_BERNARDO,Ponto.TERMINAL_LESTE),
    L44(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SANTO_ANDRE),

    L51(Ponto.CAMPUS_SAO_BERNARDO,Ponto.PCA_EXPEDICIONARIOS),
    L52(Ponto.PCA_EXPEDICIONARIOS,Ponto.TERMINAL_SBC),
    L53(Ponto.TERMINAL_SBC,Ponto.PCA_EXPEDICIONARIOS),
    L54(Ponto.PCA_EXPEDICIONARIOS,Ponto.CAMPUS_SAO_BERNARDO),

    L61(Ponto.CAMPUS_SANTO_ANDRE,Ponto.TERMINAL_LESTE),
    L62(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SAO_BERNARDO),
    L63(Ponto.CAMPUS_SAO_BERNARDO,Ponto.TERMINAL_LESTE),
    L64(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SANTO_ANDRE),

    L71(Ponto.CAMPUS_SANTO_ANDRE,Ponto.TERMINAL_LESTE),
    L72(Ponto.TERMINAL_LESTE,Ponto.TERMINAL_SBC),
    L73(Ponto.TERMINAL_SBC,Ponto.CAMPUS_SAO_BERNARDO),
    L74(Ponto.CAMPUS_SAO_BERNARDO,Ponto.TERMINAL_SBC),
    L75(Ponto.TERMINAL_SBC,Ponto.TERMINAL_LESTE),
    L76(Ponto.TERMINAL_LESTE,Ponto.CAMPUS_SANTO_ANDRE);



    public Ponto[] pontos;

    Linha(Ponto pt1, Ponto pt2) {
        this.pontos = new Ponto[]{pt1,pt2};
    }

    Ponto[] getPontos(){
        return pontos;
    }
}
